model:
  name: "FactorDVAE"
  group_count: 3
  n_blk_per_group: 2
  channel: 128
  hidden_dim: 128
  input_channel: 64
  codebook:
    num_embeddings: 64
    embedding_dim: 1
    init_type: "normal"
  quantizer:
    name: "GumbelQuantizer"
    temp: 1
    kl_weight: 5e-5
  discriminator:
    gamma: 5e-6
data:
  name: "MPI3DComplexDataModule"
  data_path: "./datasets/MPI3DComplex"
  img_size: 64
  num_latents: 14
  batch_size: 512
  num_workers: 8
train:
  reconst_loss: "F.mse_loss"
  max_steps: 100000
  optimizer: "torch.optim.Adam"
  vae_lr: 1e-3
  vae_lr_iter: 50000
  disc_lr: 1e-3
  disc_lr_iter: 50000
  check_val_every_n_epoch: 1
  seed: 1
